[package]
name = "variable-filter"
version = "0.1.0"
edition = "2021"
authors = ["The Muzikar"]

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = ["assert_process_allocs"] }

[workspace]
members = ["xtask"]
