name: Build on Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Verify Rust installation
        run: rustc --version

      - name: Install nih-plug
        run: cargo install --git https://github.com/robbert-vdh/nih-plug.git cargo-nih-plug

      - name: Fetch Cargo dependencies
        run: cargo fetch

      - name: Build variable-filter project with xtask
        run: cargo xtask bundle variable-filter --release

      - name: List files in the target/bundled directory
        run: ls -R ./target/bundled

      - name: Upload Build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./target/bundled
