name: Build on Ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install nih-plug
        run: sudo cargo install --git https://github.com/robbert-vdh/nih-plug.git cargo-nih-plug

      - name: Fetch Cargo dependencies
        run: cargo fetch

      - name: Build project with xtask
        run: cargo xtask bundle --release

      - name: Upload Build directory
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: Build/
