name: Create Release 

on:
  workflow_run:
    workflows: ["Automated Builds"]
    types:
      - completed

jobs:
  create_release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Create GitHub Release with Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          path: ./downloads

      - name: Create GitHub prerelease
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "prerelease-$(date -u +"%Y%m%d%H%M%S")"
          release_name: "Automated Prerelease $(date -u +"%Y-%m-%d %H:%M:%S")"
          draft: false
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Ubuntu ZIP to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./downloads/ubuntu-20.04-build.zip
          asset_name: "ubuntu-20.04-build.zip"
          asset_content_type: application/zip

      - name: Upload macOS ZIP to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./downloads/macos-universal-build.zip
          asset_name: "macos-universal-build.zip"
          asset_content_type: application/zip

      - name: Upload Windows ZIP to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./downloads/windows-build.zip
          asset_name: "windows-build.zip"
          asset_content_type: application/zip
