name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose

  build:
    name: Build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Bundle Plugin
      run: cargo xtask bundle variable-filter --release
    - name: Upload bundled plugin
      uses: actions/upload-artifact@v3
      with:
        name: bundled-plugin-windows
        path: target/self-hosted
